# This is The NumPy Tutorial
In this file are my notes for Numpy, I have also taken down the key points on my red diary for future references.

In [7]:
import numpy as np

## List VS Numpy
Numpy array can do everything a list can and more, for eg:

In [7]:
list1 = [1,2,3]
list2 = [2,3,4]
list3 = list1 * list2
print(list3)#will throw error

TypeError: can't multiply sequence by non-int of type 'list'

In [11]:
arr1 = np.array([1,2,3])
arr2 = np.array([2,3,4])
arr3 = arr1 * arr2
print(arr3) #will work

[ 2  6 12]


### Basics
##### Initializing 1D, 2D and 3D arrays:

In [17]:
arr_1d = np.array([1,2,3])
print(arr_1d)

[1 2 3]


In [21]:
arr_2d = np.array([[1.0,2.0,3.0],[1.5,2.5,3.5],[2.0,3.0,4.0]])
print(arr_2d)

[[1.  2.  3. ]
 [1.5 2.5 3.5]
 [2.  3.  4. ]]


In [27]:
arr_3d = np.array([[[1.0,2.0,3.0],[4.0,5.0,6.0],[7.0,8.0,9.0]],[[1.1,2.1,3.1],[4.1,5.1,6.1],[7.1,8.1,9.1]],[[1.2,2.2,3.2],[4.2,5.2,6.2],[7.2,8.2,9.2]]])
print(arr_3d)

[[[1.  2.  3. ]
  [4.  5.  6. ]
  [7.  8.  9. ]]

 [[1.1 2.1 3.1]
  [4.1 5.1 6.1]
  [7.1 8.1 9.1]]

 [[1.2 2.2 3.2]
  [4.2 5.2 6.2]
  [7.2 8.2 9.2]]]


##### Get Dimentions of an array:

In [32]:
arr_1d.ndim

1

In [34]:
arr_2d.ndim

2

In [36]:
arr_3d.ndim

3

##### Get Shape of an array:

In [41]:
arr_1d.shape

(3,)

In [43]:
arr_2d.shape

(3, 3)

In [45]:
arr_3d.shape

(3, 3, 3)

##### Specifying and checking datatypes:

In [48]:
arr_1 = np.array([1,2,3], dtype="int8")
arr_1.dtype

dtype('int8')

In [50]:
arr_2d.dtype

dtype('float64')

##### Different Size Retreival

itemsize : Returns the size of individual items

In [56]:
print(arr_1.itemsize)
print(arr_1d.itemsize)
print(arr_2d.itemsize)

1
4
8


size : Returns number of elements in an array

In [60]:
print(arr_1.size)
print(arr_2d.size)

3
9


nbytes : Returns total number of bytes of an array

In [63]:
print(arr_1.nbytes)
print(arr_1d.nbytes)
print(arr_2d.nbytes)

3
12
72


### Accessing Elements from MultiDimentional Array

In [68]:
arr_2 = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
arr_2

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

##### Getting Specific Element
arr[Row,Col]

In [78]:
print(arr_2[1,2])
arr_2[-1,-2]

10


13

##### Getting an entire row or col
arr[Row , :] selects an entire row <br/> 
arr[: , Col] selects an entire column

In [82]:
print(arr_2[1,:]) #Prints 2nd Row

[ 8  9 10 11 12 13 14]


In [86]:
print(arr_2[:,3]) #Prints 4th Column

[ 4 11]


##### Actual Format of Access:
arr[row start:end:step, col start:end:step]

In [97]:
arr_3 = np.array([[10,20,30,40,50,60,70,80,90,11,21,31],[41,51,61,71,81,91,12,22,32,42,52,62],[42,52,62,72,82,92,13,23,33,43,53,63]])
arr_3

array([[10, 20, 30, 40, 50, 60, 70, 80, 90, 11, 21, 31],
       [41, 51, 61, 71, 81, 91, 12, 22, 32, 42, 52, 62],
       [42, 52, 62, 72, 82, 92, 13, 23, 33, 43, 53, 63]])

In [101]:
arr_3[0:3:2,1:-2:2] #selects all rows skipping 1 each time from 0 to 3, selects all columns from the selected rows betweem 1 and -2 skipping 1

array([[20, 40, 60, 80, 11],
       [52, 72, 92, 23, 43]])

### Modifying Array:

##### Simple Modify:

In [105]:
arr_3[1,2] = 69 # replaces 62 with 69
arr_3

array([[10, 20, 30, 40, 50, 60, 70, 80, 90, 11, 21, 31],
       [41, 51, 69, 71, 81, 91, 12, 22, 32, 42, 52, 62],
       [42, 52, 62, 72, 82, 92, 13, 23, 33, 43, 53, 63]])

##### Sequence Modify:

In [110]:
arr_3[0:3:2,1:-2:2] = [[29, 49, 69, 89, 19],[59, 79, 99, 29, 49]]
arr_3

array([[10, 29, 30, 49, 50, 69, 70, 89, 90, 19, 21, 31],
       [41, 51, 69, 71, 81, 91, 12, 22, 32, 42, 52, 62],
       [42, 59, 62, 79, 82, 99, 13, 29, 33, 49, 53, 63]])

### Various Initialization methods:

##### All Zero Matrix:

In [119]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

##### All Ones Matrix:

In [134]:
om = np.ones((3,5))
om

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

##### All n Matrix (n=7, Thala for a Reason)

In [129]:
np.full((7,7),7) #Thala Matrix

array([[7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7]])

##### Make n Matrix by copying shape:

In [136]:
np.full_like(om,7)

array([[7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.]])

##### Identity matrix of nxn:

In [139]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

##### Repeat Matrix:

In [148]:
a1 = np.array([[1,2,3]])
a1

array([[1, 2, 3]])

In [154]:
r1 = np.repeat(a1,3)
r1

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [156]:
r2 = np.repeat(a1,3,axis=0)
r2

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

##### Random Sample Matrix:

In [161]:
np.random.rand(4,2)

array([[0.71706828, 0.3996607 ],
       [0.22776945, 0.7719433 ],
       [0.32484539, 0.56902596],
       [0.589074  , 0.75179088]])

In [163]:
np.random.randint(4,8,size=(3,3))

array([[5, 4, 5],
       [6, 7, 7],
       [6, 5, 5]])

In [165]:
np.random.sample(om.shape)

array([[0.61329205, 0.83677012, 0.52998948, 0.93521466, 0.80722547],
       [0.39078922, 0.25091521, 0.72070846, 0.75648034, 0.73454036],
       [0.49713436, 0.55792503, 0.49713707, 0.52003602, 0.89134089]])

### Safe Copy of array:

##### Unsafe Method:

In [173]:
a = np.array([1,2,3])
b = a
b[0] = 69
print(b)
print(a)

[69  2  3]
[69  2  3]


##### Safe Method:

In [176]:
a1 = np.array([1,2,3])
b1 = a1.copy()
b1[0] = 69
print(b1)
print(a1)

[69  2  3]
[1 2 3]


### Mathematics in NumPy Arrays:

##### Single Array Operations:

In [11]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [13]:
a+2

array([3, 4, 5, 6])

In [15]:
a-2

array([-1,  0,  1,  2])

In [17]:
a*2

array([2, 4, 6, 8])

In [19]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [21]:
a//2

array([0, 1, 1, 2], dtype=int32)

In [23]:
a%2

array([1, 0, 1, 0], dtype=int32)

In [25]:
a**2

array([ 1,  4,  9, 16])

In [27]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [29]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [31]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

In [33]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

##### 1D arrays Operations:

In [36]:
b = np.array([0,1,0,1])

In [38]:
a

array([1, 2, 3, 4])

In [40]:
b

array([0, 1, 0, 1])

In [42]:
a+b

array([1, 3, 3, 5])

In [44]:
a-b

array([1, 1, 3, 3])

In [46]:
a*b

array([0, 2, 0, 4])

In [48]:
a/b

C:\Users\siddh\AppData\Local\Temp\ipykernel_19368\1348051284.py:1: RuntimeWarning: divide by zero encountered in divide
  a/b


array([inf,  2., inf,  4.])

In [50]:
b = np.array([1,2,1,2])

In [52]:
a/b

array([1., 1., 3., 2.])

In [54]:
a*b

array([1, 4, 3, 8])

In [56]:
a**b

array([ 1,  4,  3, 16])

In [58]:
a//b

array([1, 1, 3, 2])

In [60]:
a%b

array([0, 0, 0, 0])

##### 2D Arrays Operations:

In [63]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
d = np.array([[3,2,1],[6,5,4],[9,8,7]])

In [65]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
d

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [69]:
c*d

array([[ 3,  4,  3],
       [24, 25, 24],
       [63, 64, 63]])

In [71]:
np.dot(c,d)

array([[ 42,  36,  30],
       [ 96,  81,  66],
       [150, 126, 102]])

In [73]:
np.cross(c,d)

array([[ -4,   8,  -4],
       [-10,  20, -10],
       [-16,  32, -16]])

In [75]:
np.matrix(c)

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [77]:
np.matrix(c)*np.matrix(d)

matrix([[ 42,  36,  30],
        [ 96,  81,  66],
        [150, 126, 102]])

In [83]:
x = np.array([2,4,8])
y = np.array([6,4,2])

In [85]:
x

array([2, 4, 8])

In [87]:
y

array([6, 4, 2])

In [89]:
np.cross(x,y)

array([-24,  44, -16])

In [91]:
np.matmul(c,d)

array([[ 42,  36,  30],
       [ 96,  81,  66],
       [150, 126, 102]])

In [93]:
z = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
z

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [95]:
np.linalg.det(z)

-9.51619735392994e-16

In [97]:
i = np.identity(3)
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [99]:
np.linalg.det(i)

1.0

In [101]:
a1 = np.matrix([[2,5,3],[1,0,6],[8,-1,2]])
a1

matrix([[ 2,  5,  3],
        [ 1,  0,  6],
        [ 8, -1,  2]])

In [103]:
np.linalg.det(a1)

238.99999999999986

### Aggrigates in NumPy:

In [107]:
s = np.array([[1,2,3],[4,5,6]])

##### Min
Note: axis = 0 -> column wise ; axis = 1 -> row wise

In [110]:
np.min(s)

1

In [112]:
np.min(s,axis=0)

array([1, 2, 3])

In [114]:
np.min(s,axis=1)

array([1, 4])

##### Max

In [117]:
np.max(s)

6

In [119]:
np.max(s,axis=0)

array([4, 5, 6])

In [121]:
np.max(s,axis=1)

array([3, 6])

##### Sum

In [124]:
np.sum(s)

21

In [126]:
np.sum(s,axis=0)

array([5, 7, 9])

In [128]:
np.sum(s,axis=1)

array([ 6, 15])

##### Average

In [133]:
np.average(s)

3.5

In [136]:
np.average(s,axis=0)

array([2.5, 3.5, 4.5])

In [138]:
np.average(s,axis=1)

array([2., 5.])

##### count

In [143]:
np.size(s)

6

In [145]:
np.size(s,axis=0)

2

In [147]:
np.size(s,axis=1)

3

### Re-Organising Arrays:

##### ReShape:

In [151]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [155]:
a.reshape((4,2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [157]:
a.reshape((2,2,2))

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [163]:
a.reshape((8,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

##### Vertical Stacking:

In [168]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [172]:
b = np.array([5,6,7,8])
b

array([5, 6, 7, 8])

In [174]:
np.vstack([a,b])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [189]:
np.vstack([a,b,a,b])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

##### Horizontal Stack

In [177]:
np.hstack([a,b])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [181]:
c = np.array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [183]:
d = np.array([[11,21,31],[41,51,61]])
d

array([[11, 21, 31],
       [41, 51, 61]])

In [185]:
np.hstack([c,d])

array([[ 1,  2,  3, 11, 21, 31],
       [ 4,  5,  6, 41, 51, 61]])

In [187]:
np.vstack([c,d])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 21, 31],
       [41, 51, 61]])

### Reading Data From File:

In [196]:
np.genfromtxt('data.txt', delimiter=",", dtype="int16")

array([[10, 20, 30, 40, 50, 60, 70, 80, 90],
       [11, 21, 31, 41, 51, 61, 71, 81, 91],
       [12, 22, 32, 42, 52, 62, 72, 82, 92]], dtype=int16)

### Type changing:

In [208]:
a = np.array([1.5,2.0,3.0])
a

array([1.5, 2. , 3. ])

In [210]:
b = a.astype('int8')
b

array([1, 2, 3], dtype=int8)

### Boolean Masking:

In [215]:
x = np.random.randint(1,20,size=(3,9))
x

array([[18,  1, 11,  9, 11, 10,  6,  9, 10],
       [16, 16, 19, 12,  3, 12, 15, 14,  8],
       [16, 11, 16, 11, 14,  4, 18,  8,  2]])

In [217]:
x > 10

array([[ True, False,  True, False,  True, False, False, False, False],
       [ True,  True,  True,  True, False,  True,  True,  True, False],
       [ True,  True,  True,  True,  True, False,  True, False, False]])

In [225]:
x[x>10]

array([18, 11, 11, 16, 16, 19, 12, 12, 15, 14, 16, 11, 16, 11, 14, 18])

In [227]:
x[x>10] < 15

array([False,  True,  True, False, False, False,  True,  True, False,
        True, False,  True, False,  True,  True, False])

In [231]:
x[x>10][x[x>10]<15]

array([11, 11, 12, 12, 14, 11, 11, 14])

In [261]:
((x>10) & (x<15))

array([[False, False,  True, False,  True, False, False, False, False],
       [False, False, False,  True, False,  True, False,  True, False],
       [False,  True, False,  True,  True, False, False, False, False]])

In [263]:
x[((x>10) & (x<15))]

array([11, 11, 12, 12, 14, 11, 11, 14])

In [265]:
x[~((x>10) & (x<15))]

array([18,  1,  9, 10,  6,  9, 10, 16, 16, 19,  3, 15,  8, 16, 16,  4, 18,
        8,  2])

### List Index passing:

In [236]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,4,6]] # A list of required index can be passed to acces the specific elements in the form of an array

array([2, 5, 7])

### Any Checker:

In [240]:
a = np.array([[11,12,9,7,5],[6,5,8,13,10]])
a

array([[11, 12,  9,  7,  5],
       [ 6,  5,  8, 13, 10]])

In [242]:
np.any(a>10)

True

In [244]:
np.any(a>20)

False

In [246]:
np.any(a>10,axis=0) #col wise

array([ True,  True, False,  True, False])

In [248]:
np.any(a>12, axis=1) #row wise

array([False,  True])

### All Checker:

In [251]:
np.all(a>10)

False

In [253]:
np.all(a>2)

True

In [255]:
np.all(a>6, axis=0)

array([False, False,  True,  True, False])

In [257]:
np.all(a>5, axis=1)

array([False, False])

In [259]:
np.all(a>2, axis=1)

array([ True,  True])

### Practice Problem:
Given the following Matrix:

In [268]:
M = np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15],
              [16,17,18,19,20],
              [21,22,23,24,25],
              [26,27,28,29,30]])
M

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

##### Q1: Index [[11,12],[15,17]] from M

In [271]:
M[2:4:1,0:2:1]

array([[11, 12],
       [16, 17]])

##### Q2: Index [2,8,14,20] from M

In [298]:
M.reshape((1,30))[0,1:20:6]

array([ 2,  8, 14, 20])

In [300]:
M[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

##### Q3: Index [4,5,24,25,29,30] from M

In [328]:
M[[0,4,5]][:,3:5]

array([[ 4,  5],
       [24, 25],
       [29, 30]])

In [330]:
M[[0,4,5],3:5]

array([[ 4,  5],
       [24, 25],
       [29, 30]])